-- AlterTable
ALTER TABLE "outreach" ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "start_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "application_end" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "application_start" SET DATA TYPE TIMESTAMPTZ(3);
