import dynamic from "next/dynamic"
import Link from "next/link"
import Image from "next/image"
import { PrismaClient } from "@prisma/client"

const Grid = dynamic(()=>import('@mui/material/Grid'))
const Container = dynamic(()=>import('@mui/material/Container'))
const Stack = dynamic(()=>import('@mui/material/Stack'))
const Typography = dynamic(()=>import('@mui/material/Typography'))
const Button = dynamic(()=>import('@mui/material/Button'))
const Paper = dynamic(()=>import('@mui/material/Paper'))

const prisma = new PrismaClient()

async function CFPrograms() {
  const dccs = await prisma.dCC.findMany()
  return (
    <Grid container direction="row" spacing={2}>
      {dccs.map(dcc=>(
        <Grid item xs={6} md={4} key={dcc.short_label} className="flex items-center justify-center">
          <Link href={dcc.homepage} target="_blank" rel="noopener noreferrer"><Image src={dcc.icon || ''} alt={dcc.id} width={120} height={120}/></Link>
        </Grid>
      ))}
    </Grid>
  )
}


export default async function Home() {
  return (
    <main className="mt-24">
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Stack spacing={3}>
            <Typography variant="caption" color={"primary"}>Common Fund Data Ecosystem Workbench</Typography>
            <Typography variant="h1" color="primary">
              Accelerating discovery using Common Fund Data
            </Typography>
            <Typography variant="subtitle1">
              The Common Fund Data Ecosystem (CFDE) aims to enable broad use of data generated by Common Fund Programs to accelerate hypothesis generation and discovery.
            </Typography>
            <Link href="/about">
              <Button variant="outlined" color="secondary">
                Learn More
              </Button>
            </Link>
          </Stack>
        </Grid>
        <Grid item xs={6} className="flex items-center justify-center">
          <Image src="/img/nci.jpg" alt="landing" width={400} height={400}/>
        </Grid>
        <Grid item xs={3} sx={{marginTop: 20}}>
          <Stack spacing={3}>
            <Typography variant="h2" color="primary">
              Common Fund Programs
            </Typography>
            <Typography variant="subtitle1">
            The NIH Common Fund is a funding entity within the NIH that supports bold scientific programs that catalyze discovery across all biomedical and behavioral research.
            </Typography>
          </Stack>
        </Grid>
        <Grid item xs={9} sx={{marginTop: 20}}><CFPrograms/></Grid>
        <Grid item xs={12} sx={{marginTop: 20}}>
          <Paper sx={{boxShadow: "none", background: '#FAFAFA', padding: 5, borderRadius: 15}}>
            <Grid container spacing={2}>
              <Grid item xs={12} md={6} className="flex items-center justify-center">
                <Image src="/img/FAIR.jpg" alt="fair" width={400} height={400}/>
              </Grid>
              <Grid item xs={12} md={6}>
                <Typography variant={"h2"} color="primary">
                  Making data more FAIR
                </Typography>
                <Typography variant={"subtitle1"}>
                  The Data Resource and Knowledge Centers are dedicated to enhancing the accessibility and utility of Common Fund-generated data and resources, striving to uphold the FAIR principles. This commitment serves as a catalyst for groundbreaking biomedical discoveries, fostering synergies across the diverse datasets within the Common Fund ecosystem, thereby unlocking novel avenues of research and innovation.
                </Typography>
                <div  className="mt-5">
                  <Typography variant={"caption"}>
                    What is FAIR?
                  </Typography>
                </div>
                <div  className="ml-8">
                  <ul>
                    <li style={{listStyleType: "disc"}}><Typography variant={"caption"}>Findable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"caption"}>Accessible</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"caption"}>Interoperable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"caption"}>Reusable</Typography></li>
                  </ul>
                </div>
              </Grid>
            </Grid>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Paper sx={{
                      boxShadow: "none", 
                      background: '#FAFAFA',
                      padding: 5, 
                      borderRadius: 0, 
                      width: "100vw", 
                      marginLeft: "calc((-100vw + 100%) / 2)", 
                      marginRight: "calc((-100vw + 100%) / 2)"}}>
            <Container maxWidth={"lg"}>
              <Grid container spacing={2} justifyContent={"space-between"} alignItems={"center"}>
                <Grid item>
                  <Typography variant={"h2"}>
                    Standards & Protocols
                  </Typography>
                  <Typography variant={"subtitle1"}>
                    Learn more about the standards and protocols for accessing and submitting data to the portal
                  </Typography>
                </Grid>
                <Grid item>
                  <Link href="/">
                    <Button variant="contained" color="secondary">Know More</Button>
                  </Link>
                </Grid>
              </Grid>
            </Container>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 20, textAlign: "center"}}>
          <Typography variant={"h2"}>
            Training & Outreach
          </Typography>
        </Grid>
      </Grid>
    </main>
  )
}
