MATCH ()-[r:GENERATED_BY_ANALYSIS_TYPE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:REGISTERED]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:SUBJECT_TESTED_FOR_PHENOTYPE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_RACE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_DISEASE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_PARENT_OF]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DCC_CONTAINS_PROJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ID_NAMESPACE_CONTAINS_PROJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:GENE_HAS_SOURCE_NCBI_TAXONOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PHENOTYPE_ASSOCIATED_WITH_GENE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_ETHNICITY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_SUPERSET_OF]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:SUBJECT_TESTED_FOR_DISEASE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:SUBSTANCE_ASSOCIATED_WITH_COMPOUND]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_GENE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_SEX]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_COMPOUND]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_ANATOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_BIOFLUID]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_PHENOTYPE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_SUBSTANCE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:SUBJECT_ASSOCIATED_WITH_NCBI_TAXONOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_GRANULARITY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PROJECT_CONTAINS_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ID_NAMESPACE_CONTAINS_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DCC_CONTAINS_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_BIOSAMPLE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PROTEIN_HAS_SOURCE_NCBI_TAXONOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:HAS_SOURCE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_PROTEIN]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_NCBI_TAXONOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DEFINED_BY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ID_NAMESPACE_CONTAINS_COLLECTION]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DCC_CONTAINS_COLLECTION]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:BIOSAMPLE_ASSOCIATED_WITH_SUBSTANCE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:BIOSAMPLE_TESTED_FOR_DISEASE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:BIOSAMPLE_SAMPLED_FROM_ANATOMY]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:BIOSAMPLE_SAMPLED_FROM_BIOFLUID]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:TESTED_FOR]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ASSOCIATED_WITH]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PREPPED_VIA]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:HAS_SYNONYM]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:BIOSAMPLE_SAMPLED_FROM_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:SAMPLED_FROM]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PROJECT_CONTAINS_BIOSAMPLE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DCC_CONTAINS_BIOSAMPLE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ID_NAMESPACE_CONTAINS_BIOSAMPLE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_DATA_TYPE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:FILE_DESCRIBES_SUBJECT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:FILE_DESCRIBES_BIOSAMPLE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DESCRIBES]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:COLLECTION_CONTAINS_FILE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:GENERATED_BY_ASSAY_TYPE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:DCC_CONTAINS_FILE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:PROJECT_CONTAINS_FILE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:ID_NAMESPACE_CONTAINS_FILE]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:IS_FILE_FORMAT]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;

MATCH ()-[r:CONTAINS]->()
CALL {
    WITH r
    DELETE r
} IN TRANSACTIONS OF 10000 ROWS;
