#!/bin/bash
set -e

cypher-shell -p $PASSWORD -u $USERNAME "CREATE USER $C2M2_READER_USERNAME IF NOT EXISTS\
SET PASSWORD '$C2M2_READER_PASSWORD' CHANGE NOT REQUIRED\
SET STATUS ACTIVE\
SET HOME DATABASE $C2M2_DBNAME\
GRANT ACCESS ON DATABASE $C2M2_DBNAME TO $C2M2_READER_USERNAME\
GRANT MATCH {*} ON GRAPH $C2M2_DBNAME NODES * TO PUBLIC\
GRANT MATCH {*} ON GRAPH $C2M2_DBNAME RELATIONSHIPS * TO PUBLIC
"
