#!/bin/bash
set -e

cypher-shell -p $NEO4J_PASSWORD -u $NEO4J_USERNAME "CREATE USER $NEO4J_C2M2_READER_USERNAME IF NOT EXISTS\
SET PASSWORD '$NEO4J_C2M2_READER_PASSWORD' CHANGE NOT REQUIRED\
SET STATUS ACTIVE\
SET HOME DATABASE $NEO4J_C2M2_DBNAME\
GRANT ACCESS ON DATABASE $NEO4J_C2M2_DBNAME TO $NEO4J_C2M2_READER_USERNAME\
GRANT MATCH {*} ON GRAPH $NEO4J_C2M2_DBNAME NODES * TO PUBLIC\
GRANT MATCH {*} ON GRAPH $NEO4J_C2M2_DBNAME RELATIONSHIPS * TO PUBLIC
"
