set statement_timeout = 0;
	DROP INDEX IF EXISTS c2m2.c2m2_file_idx_searchable;
		CREATE INDEX c2m2_file_idx_searchable ON c2m2.file USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_idx_searchable;
		CREATE INDEX c2m2_biosample_idx_searchable ON c2m2.biosample USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_idx_searchable;
		CREATE INDEX c2m2_subject_idx_searchable ON c2m2.subject USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_dcc_idx_searchable;
		CREATE INDEX c2m2_dcc_idx_searchable ON c2m2.dcc USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_project_idx_searchable;
		CREATE INDEX c2m2_project_idx_searchable ON c2m2.project USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_project_in_project_idx_searchable;
		CREATE INDEX c2m2_project_in_project_idx_searchable ON c2m2.project_in_project USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_idx_searchable;
		CREATE INDEX c2m2_collection_idx_searchable ON c2m2.collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_in_collection_idx_searchable;
		CREATE INDEX c2m2_collection_in_collection_idx_searchable ON c2m2.collection_in_collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_file_describes_collection_idx_searchable;
		CREATE INDEX c2m2_file_describes_collection_idx_searchable ON c2m2.file_describes_collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_defined_by_project_idx_searchable;
		CREATE INDEX c2m2_collection_defined_by_project_idx_searchable ON c2m2.collection_defined_by_project USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_file_in_collection_idx_searchable;
		CREATE INDEX c2m2_file_in_collection_idx_searchable ON c2m2.file_in_collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_in_collection_idx_searchable;
		CREATE INDEX c2m2_biosample_in_collection_idx_searchable ON c2m2.biosample_in_collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_in_collection_idx_searchable;
		CREATE INDEX c2m2_subject_in_collection_idx_searchable ON c2m2.subject_in_collection USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_file_describes_biosample_idx_searchable;
		CREATE INDEX c2m2_file_describes_biosample_idx_searchable ON c2m2.file_describes_biosample USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_file_describes_subject_idx_searchable;
		CREATE INDEX c2m2_file_describes_subject_idx_searchable ON c2m2.file_describes_subject USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_from_subject_idx_searchable;
		CREATE INDEX c2m2_biosample_from_subject_idx_searchable ON c2m2.biosample_from_subject USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_disease_idx_searchable;
		CREATE INDEX c2m2_biosample_disease_idx_searchable ON c2m2.biosample_disease USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_disease_idx_searchable;
		CREATE INDEX c2m2_subject_disease_idx_searchable ON c2m2.subject_disease USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_disease_idx_searchable;
		CREATE INDEX c2m2_collection_disease_idx_searchable ON c2m2.collection_disease USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_phenotype_idx_searchable;
		CREATE INDEX c2m2_collection_phenotype_idx_searchable ON c2m2.collection_phenotype USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_gene_idx_searchable;
		CREATE INDEX c2m2_collection_gene_idx_searchable ON c2m2.collection_gene USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_compound_idx_searchable;
		CREATE INDEX c2m2_collection_compound_idx_searchable ON c2m2.collection_compound USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_substance_idx_searchable;
		CREATE INDEX c2m2_collection_substance_idx_searchable ON c2m2.collection_substance USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_taxonomy_idx_searchable;
		CREATE INDEX c2m2_collection_taxonomy_idx_searchable ON c2m2.collection_taxonomy USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_anatomy_idx_searchable;
		CREATE INDEX c2m2_collection_anatomy_idx_searchable ON c2m2.collection_anatomy USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_biofluid_idx_searchable;
		CREATE INDEX c2m2_collection_biofluid_idx_searchable ON c2m2.collection_biofluid USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_protein_idx_searchable;
		CREATE INDEX c2m2_collection_protein_idx_searchable ON c2m2.collection_protein USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_phenotype_idx_searchable;
		CREATE INDEX c2m2_subject_phenotype_idx_searchable ON c2m2.subject_phenotype USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_substance_idx_searchable;
		CREATE INDEX c2m2_biosample_substance_idx_searchable ON c2m2.biosample_substance USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_substance_idx_searchable;
		CREATE INDEX c2m2_subject_substance_idx_searchable ON c2m2.subject_substance USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_gene_idx_searchable;
		CREATE INDEX c2m2_biosample_gene_idx_searchable ON c2m2.biosample_gene USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_phenotype_gene_idx_searchable;
		CREATE INDEX c2m2_phenotype_gene_idx_searchable ON c2m2.phenotype_gene USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_phenotype_disease_idx_searchable;
		CREATE INDEX c2m2_phenotype_disease_idx_searchable ON c2m2.phenotype_disease USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_race_idx_searchable;
		CREATE INDEX c2m2_subject_race_idx_searchable ON c2m2.subject_race USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_subject_role_taxonomy_idx_searchable;
		CREATE INDEX c2m2_subject_role_taxonomy_idx_searchable ON c2m2.subject_role_taxonomy USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_assay_type_idx_searchable;
		CREATE INDEX c2m2_assay_type_idx_searchable ON c2m2.assay_type USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_analysis_type_idx_searchable;
		CREATE INDEX c2m2_analysis_type_idx_searchable ON c2m2.analysis_type USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_ncbi_taxonomy_idx_searchable;
		CREATE INDEX c2m2_ncbi_taxonomy_idx_searchable ON c2m2.ncbi_taxonomy USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_anatomy_idx_searchable;
		CREATE INDEX c2m2_anatomy_idx_searchable ON c2m2.anatomy USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biofluid_idx_searchable;
		CREATE INDEX c2m2_biofluid_idx_searchable ON c2m2.biofluid USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_file_format_idx_searchable;
		CREATE INDEX c2m2_file_format_idx_searchable ON c2m2.file_format USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_data_type_idx_searchable;
		CREATE INDEX c2m2_data_type_idx_searchable ON c2m2.data_type USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_disease_idx_searchable;
		CREATE INDEX c2m2_disease_idx_searchable ON c2m2.disease USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_phenotype_idx_searchable;
		CREATE INDEX c2m2_phenotype_idx_searchable ON c2m2.phenotype USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_compound_idx_searchable;
		CREATE INDEX c2m2_compound_idx_searchable ON c2m2.compound USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_substance_idx_searchable;
		CREATE INDEX c2m2_substance_idx_searchable ON c2m2.substance USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_gene_idx_searchable;
		CREATE INDEX c2m2_gene_idx_searchable ON c2m2.gene USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_protein_idx_searchable;
		CREATE INDEX c2m2_protein_idx_searchable ON c2m2.protein USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_protein_gene_idx_searchable;
		CREATE INDEX c2m2_protein_gene_idx_searchable ON c2m2.protein_gene USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_sample_prep_method_idx_searchable;
		CREATE INDEX c2m2_sample_prep_method_idx_searchable ON c2m2.sample_prep_method USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_id_namespace_idx_searchable;
		CREATE INDEX c2m2_id_namespace_idx_searchable ON c2m2.id_namespace USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_collection_ptm_idx_searchable;
		CREATE INDEX c2m2_collection_ptm_idx_searchable ON c2m2.collection_ptm USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_biosample_ptm_idx_searchable;
		CREATE INDEX c2m2_biosample_ptm_idx_searchable ON c2m2.biosample_ptm USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_ptm_idx_searchable;
		CREATE INDEX c2m2_ptm_idx_searchable ON c2m2.ptm USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_ptm_type_idx_searchable;
		CREATE INDEX c2m2_ptm_type_idx_searchable ON c2m2.ptm_type USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_ptm_subtype_idx_searchable;
		CREATE INDEX c2m2_ptm_subtype_idx_searchable ON c2m2.ptm_subtype USING gin(searchable gin_trgm_ops);
	DROP INDEX IF EXISTS c2m2.c2m2_domain_location_idx_searchable;
		CREATE INDEX c2m2_domain_location_idx_searchable ON c2m2.domain_location USING gin(searchable gin_trgm_ops);
