#!/bin/bash

# To generate the folder and empty files inside the folder blank_non-auto-generated_C2M2_tables 
# given empty_tsvs and autogenerated_C2M2_term_tables folders
#
#Call syntax:
#./filter_core_empty_files.sh <SchemaUpdateFolder> <auto_folder> <output_folder>
# If Called from the SchemaUpdateFolder itself
#./filter_core_empty_files.sh . ${HOME}/CFDE/C2M2_sub/scripts/autogenerated_C2M2_term_tables blank_non-auto-generated_C2M2_tables
# Or define variables and then use in command
SchemaUpdateFolder="${HOME}/DRC/DRC-Portals/database/C2M2/SchemaUpdate"
auto_folder="${HOME}/CFDE/C2M2_sub/scripts/autogenerated_C2M2_term_tables"
output_folder="blank_non-auto-generated_C2M2_tables"
#./filter_core_empty_files.sh $SchemaUpdateFolder $auto_folder $output_folder

if [[ $# -lt 1 ]]; then
    SchemaUpdateFolder="${HOME}/DRC/DRC-Portals/database/C2M2/SchemaUpdate"
else
    SchemaUpdateFolder="$1"
fi

if [[ $# -lt 2 ]]; then
    auto_folder="${HOME}/CFDE/C2M2_sub/scripts/autogenerated_C2M2_term_tables"
else
    auto_folder="$2"
fi

if [[ $# -lt 3 ]]; then
    output_folder="blank_non-auto-generated_C2M2_tables"
else
    output_folder="$3"
fi

#SchemaUpdateFolder="$1"
#auto_folder="$2"
#output_folder="$3"

# Define the folder paths
#SchemaUpdateFolder="${HOME}/DRC/DRC-Portals/database/C2M2/SchemaUpdate"
#empty_folder="empty_tsvs_2024-11"
empty_folder="${SchemaUpdateFolder}/empty_tsvs"
#auto_folder="${HOME}/CFDE/C2M2_sub/scripts/autogenerated_C2M2_term_tables"
#output_folder="blank_non-auto-generated_C2M2_tables"

# Create the output folder if it doesn't exist
mkdir -p "$output_folder"

# delete existing tsv files in the output folder
rm -rf ${output_folder}/*.tsv

# Find and copy files from the empty folder that are not in the auto folder
for file in "$empty_folder"/*.tsv; do
    filename=$(basename "$file")
    if [ ! -f "$auto_folder/$filename" ]; then
        cp "$file" "$output_folder/"
    fi
done

zip -r ${output_folder}.zip ${output_folder}

echo "Files copied to $output_folder and zipped"

