services:
  neo4j:
    image: neo4j:5.22.0-enterprise-bullseye
    container_name: drc-portals-neo4j-load
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
      - ./backups:/backups
    environment:
      - USERNAME
      - PASSWORD
      - DB_ADDRESS
      - NEO4J_AUTH
      - GRAPH_C2M2_DBNAME
      - GRAPH_C2M2_READER_USERNAME
      - GRAPH_C2M2_READER_PASSWORD
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_cypher_lenient__create__relationship=true
      - NEO4JLABS_PLUGINS=["apoc"]
