version: '3'
services:
  neo4j:
    image: neo4j:5.16.0-enterprise-bullseye
    container_name: drc-portals-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./import:/import
      - drc-portals-neo4j-data:/var/lib/neo4j/data
    environment:
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
      - NEO4J_C2M2_DBNAME
      - NEO4J_C2M2_READER_USERNAME
      - NEO4J_C2M2_READER_PASSWORD
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_cypher_lenient__create__relationship=true
      - NEO4J_dbms_transaction_timeout=2m
      - NEO4J_dbms_lock_acquisition_timeout=2m
      - NEO4J_server.directories.import=/import
      - NEO4JLABS_PLUGINS=["apoc"]

volumes:
  drc-portals-neo4j-data: