import { SchemaNodes } from "@/lib/text2cypher/schema/types";

const PROJECT = "Project";
const STUDY = "Study";
const PERSON = "Person";
const SUBJECT = "Subject";

// Analysis Related
const ANALYSIS = "Analysis";
const ANOVA = "Anova";
const CHROMATOGRAPHY = "Chromatography";
const MS = "MS";
const NMR = "NMR";
const ANALYSES: SchemaNodes = [ANOVA, CHROMATOGRAPHY, MS, NMR];

// Metadata Related
const METADATA = "Metadata";
const VERSION = "Version";
const METAS: SchemaNodes = [METADATA, VERSION];

// Sample Related
const SAMPLE = "Sample";
const SAMPLE_PREP = "SamplePrep";
const SAMPLE_SOURCE = "SampleSource";
const UNIQUE_SA = "UniqueSa";
const COLLECTION = "Collection";
const TREATMENT = "Treatment";
const SAMPLE_RELATED: SchemaNodes = [
  SAMPLE_PREP,
  SAMPLE_SOURCE,
  UNIQUE_SA,
  COLLECTION,
  TREATMENT,
];

// Factor Related
const ALL_FACTORS = "AllFactors";
const FACTOR = "Factor";
const FACTOR_LEVEL = "FactorLevel";
const FACTOR_RELATED: SchemaNodes = [ALL_FACTORS, FACTOR, FACTOR_LEVEL];

// Terms
const CLASS = "Class";
const DISEASE = "Disease";
const KINGDOM = "Kingdom";
const METABOLITE = "Metabolite";
const REFMET = "RefMet";
const SPECIES = "Species";
const TERMS: SchemaNodes = [
  CLASS,
  DISEASE,
  KINGDOM,
  METABOLITE,
  REFMET,
  SPECIES,
];

const NODES: ReadonlyArray<string> = [
  ALL_FACTORS,
  ANALYSIS,
  ANOVA,
  CHROMATOGRAPHY,
  CLASS,
  COLLECTION,
  DISEASE,
  FACTOR,
  FACTOR_LEVEL,
  KINGDOM,
  MS,
  METABOLITE,
  METADATA,
  NMR,
  PERSON,
  PROJECT,
  REFMET,
  SAMPLE,
  SAMPLE_PREP,
  SAMPLE_SOURCE,
  SPECIES,
  STUDY,
  SUBJECT,
  TREATMENT,
  UNIQUE_SA,
  VERSION,
];

const NODE_PROPERTIES: ReadonlyMap<string, ReadonlyArray<string>> = new Map([
  [ALL_FACTORS, ["factors", "factor_sort", "local_sample_id", "nodata"]],
  [
    ANALYSIS,
    [
      "id",
      "randomization_order",
      "analysis_display",
      "analysis_comments",
      "operator_name",
      "software_version",
      "results_file",
      "analysis_type",
      "data_format",
      "instrument_name",
      "acquisition_time",
      "num_factors",
      "instrument_parameters_file",
      "processing_parameters_file",
      "processed_file",
      "rt_units",
      "analysis_protocol_file",
      "num_metabolites",
      "has_mz",
      "laboratory_name",
      "units",
      "acquisition_id",
      "detector_type",
      "acquisition_parameters_file",
      "has_rt",
      "raw_file",
      "acquisition_date",
    ],
  ],
  [
    ANOVA,
    [
      "id",
      "name",
      "fdr",
      "fval",
      "factor_name",
      "analysis_type",
      "factor",
      "pval",
      "ion_mode",
    ],
  ],
  [
    CHROMATOGRAPHY,
    [
      "id",
      "running_buffer",
      "comments",
      "washing_buffer",
      "strong_wash_volume",
      "running_voltage",
      "transferline_temperature",
      "sample_injection",
      "solvent_b",
      "sampling_cone",
      "type",
      "internal_standard_mt",
      "column_temperature",
      "methods_id",
      "sample_syringe_size",
      "injection_temperature",
      "analytical_time",
      "migration_time",
      "time_program",
      "weak_wash_solvent_name",
      "solvent_c",
      "solvent_a",
      "preconditioning",
      "randomization_order",
      "sheath_liquid",
      "flow_gradient",
      "strong_wash_solvent_name",
      "retention_time",
      "sample_loop_size",
      "instrument_name",
      "oven_temperature",
      "methods_filename",
      "column_name",
      "retention_index",
      "column_pressure",
      "capillary_voltage",
      "weak_wash_volume",
      "internal_standard",
      "target_sample_temperature",
      "summary",
      "flow_rate",
    ],
  ],
  [CLASS, ["name"]],
  [
    COLLECTION,
    [
      "id",
      "protocol_id",
      "storage_vials",
      "tissue_cell_identification",
      "storage_conditions",
      "duration",
      "vials",
      "tissue_cell_quantity_taken",
      "sample_type",
      "method",
      "volume_or_amount",
      "protocol_comments",
      "protocol_filename",
      "time",
      "frequency",
      "blood_serum_or_plasma",
      "additives",
      "location",
      "tube_temp",
    ],
  ],
  [DISEASE, ["name"]],
  [FACTOR, ["id", "factor_name", "factor_description"]],
  [FACTOR_LEVEL, ["id"]],
  [KINGDOM, ["name"]],
  [
    MS,
    [
      "id",
      "reagent_gas",
      "sample_dripping",
      "collision_gas",
      "ion_mode",
      "ion_source_temperature",
      "scan_range_moverz",
      "desolvation_temperature",
      "ms_type",
      "cdl_temperature",
      "interface_voltage",
      "spray_voltage",
      "ionization_potential",
      "dry_gas_flow",
      "skimmer_voltage",
      "tube_lens_voltage",
      "capillary_temperature",
      "probe_tip",
      "dataformat",
      "gas_pressure",
      "nebulizer",
      "mass_accuracy",
      "activation_parameter",
      "desolvation_gas_flow",
      "ion_spray_voltage",
      "it_side_octopoles_bias_voltage",
      "atom_gun_current",
      "ionization",
      "fragment_voltage",
      "bombardment",
      "activation_time",
      "instrument_name",
      "precursor_type",
      "scanning",
      "ionization_energy",
      "fragmentation_method",
      "helium_flow",
      "capillary_voltage",
      "source_temperature",
      "scanning_cycle",
      "cdl_side_octopoles_bias_voltage",
      "instrument_type",
      "collision_energy",
      "dry_gas_temp",
      "automatic_gain_control",
      "ms_comments",
      "laser",
      "octpole_voltage",
      "resolution_setting",
      "scanning_range",
      "matrix",
    ],
  ],
  [
    METABOLITE,
    [
      "id",
      "name",
      "other_id_type",
      "kegg_id",
      "ri_type",
      "other_id",
      "adduct",
      "inchi_key",
      "ri",
      "standard",
      "pubchem_id",
      "moverz_quant",
    ],
  ],
  [METADATA, ["id", "local_sample_id"]],
  [
    NMR,
    [
      "id",
      "dummy_scans",
      "line_broadening",
      "num_data_points_acquired",
      "zero_filling",
      "temperature",
      "nmr_probe",
      "binned_increment",
      "pulse_sequence",
      "acquisition_time",
      "baseline_correction_method",
      "chemical_shift_ref_std",
      "receiver_gain",
      "binned_data_excluded_range",
      "power_level",
      "nmr_experiment_type",
      "relaxation_delay",
      "nmr_tube_size",
      "pulse_width",
      "shimming_method",
      "standard_concentration",
      "water_suppression",
      "chemical_shift_ref_cpd",
      "real_data_points",
      "nmr_results_file",
      "spectrometer_frequency",
      "field_frequency_lock",
      "apodization",
      "binned_data_protocol_file",
      "instrument_name",
      "number_of_scans",
      "spectral_width",
      "presaturation_power_level",
      "instrument_type",
      "nmr_solvent",
      "offset_frequency",
      "nmr_comments",
    ],
  ],
  [
    PERSON,
    [
      "id",
      "email",
      "addr_line2",
      "city",
      "country",
      "family_name",
      "given_name",
      "institution",
      "job_title",
      "laboratory",
      "password",
      "postal_code",
      "principal_investigator",
      "registration_ip",
      "request_authorization_to_upload_data",
      "state",
      "status",
      "street",
      "telephone_number",
      "timestamp",
      "unsubscribe",
      "userlevel",
      "username",
      "admin_comments",
      "mc",
      "ud",
      "department",
      "ec",
      "pi",
    ],
  ],
  [
    PROJECT,
    [
      "id",
      "email",
      "laboratory",
      "department",
      "address",
      "institute",
      "comments",
      "last_name",
      "doi",
      "title",
      "publication_doi",
      "summary",
      "phone",
      "funding_source",
      "first_name",
      "publications",
      "contributors",
      "type",
    ],
  ],
  [
    REFMET,
    [
      "name",
      "status",
      "alt_name",
      "comments",
      "sys_name",
      "formula",
      "pubchem_cid",
      "regno",
      "exactmass",
      "chebi_id",
      "grp",
      "idx",
      "group_id",
      "super_class",
      "map_regno",
      "kegg_id",
      "main_class",
      "bulk",
      "inchi_key",
      "contains_sugar",
      "inchi",
      "smiles",
      "sub_class",
      "refmet_id",
    ],
  ],
  [SAMPLE, ["id", "local_subject_id", "data", "local_sample_id"]],
  [
    SAMPLE_PREP,
    [
      "id",
      "extract_concentration_dilution",
      "protocol_id",
      "sample_resuspension",
      "organ",
      "organ_specification",
      "extract_storage",
      "extract_enrichment",
      "processing_method",
      "subcellular_location",
      "protocol_comments",
      "protocol_filename",
      "cell_type",
      "processing_storage_conditions",
      "extract_cleanup",
      "sample_derivatization",
      "summary",
      "extraction_method",
      "sample_spiking",
    ],
  ],
  [SAMPLE_SOURCE, ["name"]],
  [SPECIES, ["name", "common_name", "taxonomy_ids"]],
  [
    STUDY,
    [
      "id",
      "email",
      "laboratory",
      "department",
      "address",
      "institute",
      "comments",
      "chear_study",
      "last_name",
      "num_females",
      "file_type",
      "submit_date",
      "raw_data_status",
      "first_name",
      "size",
      "type",
      "num_males",
      "total_subjects",
      "num_groups",
      "title",
      "summary",
      "analysis_type_detail",
      "phone",
      "publications",
    ],
  ],
  [
    SUBJECT,
    [
      "id",
      "human_prescription_otc",
      "cell_passage_number",
      "human_trial_type",
      "human_race",
      "human_alcohol_drug_use",
      "cell_biosource_or_supplier",
      "cell_primary_immortalized",
      "human_inclusion_criteria",
      "human_lifestyle_factors",
      "animal_light_cycle",
      "human_ethnicity",
      "weight_or_weight_range",
      "genotype_strain",
      "cell_strain_details",
      "animal_housing",
      "age_or_age_range",
      "human_exclusion_criteria",
      "type",
      "animal_animal_supplier",
      "human_smoking_status",
      "animal_feed",
      "animal_water",
      "species_group",
      "animal_inclusion_criteria",
      "gender",
      "subject_comments",
      "human_medications",
      "height_or_height_range",
      "cell_counts",
      "human_nutrition",
    ],
  ],
  [
    TREATMENT,
    [
      "id",
      "protocol_id",
      "animal_vet_treatments",
      "treatment",
      "human_fasting",
      "animal_acclimation_duration",
      "plant_growth_stage",
      "dose_duration",
      "cell_pct_confluence",
      "compound",
      "plant_plot_design",
      "animal_anesthesia",
      "cell_inoc_proc",
      "protocol_comments",
      "plant_metab_quench_method",
      "cell_growth_config",
      "animal_endp_tissue_coll_list",
      "plant_harvest_method",
      "vehicle",
      "animal_endp_euthanasia",
      "plant_temp",
      "route",
      "cell_harvesting",
      "plant_estab_date",
      "plant_growth_location",
      "cell_media",
      "animal_fasting",
      "plant_watering_regime",
      "cell_media_lastchanged",
      "plant_light_period",
      "plant_storage",
      "plant_humidity",
      "plant_harvest_date",
      "animal_endp_clinical_signs",
      "dose",
      "cell_growth_container",
      "plant_nutritional_regime",
      "protocol_filename",
      "cell_envir_cond",
      "plant_growth_support",
      "human_endp_clinical_signs",
      "dose_volume",
      "cell_growth_rate",
      "animal_endp_tissue_proc_method",
      "summary",
      "cell_storage",
    ],
  ],
  [UNIQUE_SA, ["id", "source", "raw_data", "local_sample_id"]],
  [VERSION, ["version"]],
]);

const ANALYSIS_REFERENCES_METABOLITE = "ANALYSIS_REFERENCES_METABOLITE";
const ANALYSIS_USED_ANOVA = "ANALYSIS_USED_ANOVA";
const ANOVA_REFERENCES_REFMET = "ANOVA_REFERENCES_REFMET";
const BELONGS_TO_CLASS = "BELONGS_TO_CLASS";
const BELONGS_TO_KINGDOM = "BELONGS_TO_KINGDOM";
const COLLECTION_LINKED_TO_METADATA = "COLLECTION_LINKED_TO_METADATA";
const COLLECTED_FROM_SUBJECT = "COLLECTED_FROM_SUBJECT";
const DERIVED_FROM_CHROMATOGRAPHY = "DERIVED_FROM_CHROMATOGRAPHY";
const DERIVED_FROM_MS = "DERIVED_FROM_MS";
const DERIVED_FROM_NMR = "DERIVED_FROM_NMR";
const FACTOR_LEVEL_HAS_FACTOR = "FACTOR_LEVEL_HAS_FACTOR";
const HAS_FACTORS = "HAS_FACTORS";
const HAS_VERSION = "HAS_VERSION";
const INCLUDES_STUDY = "INCLUDES_STUDY";
const IS_CONTACT_FOR = "IS_CONTACT_FOR";
const IS_SPECIES = "IS_SPECIES";
const METABOLITE_LINKED_TO_REFMET = "METABOLITE_LINKED_TO_REFMET";
const REFERENCES_DISEASE = "REFERENCES_DISEASE";
const SAMPLED_FROM_SOURCE = "SAMPLED_FROM_SOURCE";
const SAMPLED_FROM_SPECIES = "SAMPLED_FROM_SPECIES";
const SAMPLED_FROM_SUBJECT = "SAMPLED_FROM_SUBJECT";
const SAMPLE_PREP_LINKED_TO_METADATA = "SAMPLE_PREP_LINKED_TO_METADATA";
const SAMPLE_TAKEN_FROM = "SAMPLE_TAKEN_FROM";
const SAMPLE_USES_FACTOR_LEVEL = "SAMPLE_USES_FACTOR_LEVEL";
const STUDY_PRODUCED_ANALYSIS = "STUDY_PRODUCED_ANALYSIS";
const STUDY_PRODUCED_ANOVA = "STUDY_PRODUCED_ANOVA";
const STUDY_REFERENCES_METABOLITE = "STUDY_REFERENCES_METABOLITE";
const STUDY_REFERENCES_SOURCE = "STUDY_REFERENCES_SOURCE";
const STUDY_REFERENCES_UNIQUE_SA = "STUDY_REFERENCES_UNIQUE_SA";
const TREATMENT_LINKED_TO_METADATA = "TREATMENT_LINKED_TO_METADATA";
const UNIQUE_SA_SAMPLED_FROM_SOURCE = "UNIQUE_SA_SAMPLED_FROM_SOURCE";

const RELATIONSHIPS: ReadonlyArray<string> = [
  ANALYSIS_REFERENCES_METABOLITE,
  ANALYSIS_USED_ANOVA,
  ANOVA_REFERENCES_REFMET,
  BELONGS_TO_CLASS,
  BELONGS_TO_KINGDOM,
  COLLECTION_LINKED_TO_METADATA,
  COLLECTED_FROM_SUBJECT,
  DERIVED_FROM_CHROMATOGRAPHY,
  DERIVED_FROM_MS,
  DERIVED_FROM_NMR,
  FACTOR_LEVEL_HAS_FACTOR,
  HAS_FACTORS,
  HAS_VERSION,
  INCLUDES_STUDY,
  IS_CONTACT_FOR,
  IS_SPECIES,
  METABOLITE_LINKED_TO_REFMET,
  REFERENCES_DISEASE,
  SAMPLED_FROM_SOURCE,
  SAMPLED_FROM_SPECIES,
  SAMPLED_FROM_SUBJECT,
  SAMPLE_PREP_LINKED_TO_METADATA,
  SAMPLE_TAKEN_FROM,
  SAMPLE_USES_FACTOR_LEVEL,
  STUDY_PRODUCED_ANALYSIS,
  STUDY_PRODUCED_ANOVA,
  STUDY_REFERENCES_METABOLITE,
  STUDY_REFERENCES_SOURCE,
  STUDY_REFERENCES_UNIQUE_SA,
  TREATMENT_LINKED_TO_METADATA,
  UNIQUE_SA_SAMPLED_FROM_SOURCE,
];

const PATHWAYS: ReadonlyArray<[string, string, string]> = [
  [ANALYSIS, ANALYSIS_REFERENCES_METABOLITE, METABOLITE],
  [ANALYSIS, ANALYSIS_USED_ANOVA, ANOVA],
  [ANOVA, ANOVA_REFERENCES_REFMET, REFMET],
  [SPECIES, BELONGS_TO_CLASS, CLASS],
  [SPECIES, BELONGS_TO_KINGDOM, KINGDOM],
  [COLLECTION, COLLECTION_LINKED_TO_METADATA, METADATA],
  [COLLECTION, COLLECTED_FROM_SUBJECT, SUBJECT],
  [ANALYSIS, DERIVED_FROM_CHROMATOGRAPHY, CHROMATOGRAPHY],
  [ANALYSIS, DERIVED_FROM_MS, MS],
  [ANALYSIS, DERIVED_FROM_NMR, NMR],
  [FACTOR_LEVEL, FACTOR_LEVEL_HAS_FACTOR, FACTOR],
  [SAMPLE, HAS_FACTORS, ALL_FACTORS],
  [STUDY, HAS_VERSION, VERSION],
  [PROJECT, INCLUDES_STUDY, STUDY],
  [PERSON, IS_CONTACT_FOR, STUDY],
  [PERSON, IS_CONTACT_FOR, PROJECT],
  [SUBJECT, IS_SPECIES, SPECIES],
  [METABOLITE, METABOLITE_LINKED_TO_REFMET, REFMET],
  [STUDY, REFERENCES_DISEASE, DISEASE],
  [SAMPLE, SAMPLED_FROM_SOURCE, SAMPLE_SOURCE],
  [SAMPLE, SAMPLED_FROM_SPECIES, SPECIES],
  [SAMPLE_PREP, SAMPLE_PREP_LINKED_TO_METADATA, METADATA],
  [SAMPLE, SAMPLE_TAKEN_FROM, SUBJECT],
  [SAMPLE, SAMPLE_USES_FACTOR_LEVEL, FACTOR_LEVEL],
  [SAMPLE_PREP, SAMPLED_FROM_SUBJECT, SUBJECT],
  [STUDY, STUDY_PRODUCED_ANALYSIS, ANALYSIS],
  [STUDY, STUDY_PRODUCED_ANOVA, ANOVA],
  [STUDY, STUDY_REFERENCES_METABOLITE, METABOLITE],
  [STUDY, STUDY_REFERENCES_SOURCE, SAMPLE_SOURCE],
  [STUDY, STUDY_REFERENCES_UNIQUE_SA, UNIQUE_SA],
  [TREATMENT, TREATMENT_LINKED_TO_METADATA, METADATA],
  [UNIQUE_SA, UNIQUE_SA_SAMPLED_FROM_SOURCE, SAMPLE_SOURCE],
];

const schema = {
  ALL_FACTORS,
  ANALYSIS,
  ANALYSES,
  ANOVA,
  CHROMATOGRAPHY,
  CLASS,
  COLLECTION,
  DISEASE,
  FACTOR,
  FACTOR_LEVEL,
  KINGDOM,
  MS,
  METABOLITE,
  METADATA,
  METAS,
  NMR,
  PERSON,
  PROJECT,
  REFMET,
  SAMPLE,
  SAMPLE_PREP,
  SAMPLE_SOURCE,
  SPECIES,
  STUDY,
  SUBJECT,
  TREATMENT,
  UNIQUE_SA,
  VERSION,
  FACTOR_RELATED,
  SAMPLE_RELATED,
  TERMS,
  ANALYSIS_REFERENCES_METABOLITE,
  ANALYSIS_USED_ANOVA,
  ANOVA_REFERENCES_REFMET,
  BELONGS_TO_CLASS,
  BELONGS_TO_KINGDOM,
  COLLECTION_LINKED_TO_METADATA,
  COLLECTED_FROM_SUBJECT,
  DERIVED_FROM_CHROMATOGRAPHY,
  DERIVED_FROM_MS,
  DERIVED_FROM_NMR,
  FACTOR_LEVEL_HAS_FACTOR,
  HAS_FACTORS,
  HAS_VERSION,
  INCLUDES_STUDY,
  IS_CONTACT_FOR,
  IS_SPECIES,
  METABOLITE_LINKED_TO_REFMET,
  REFERENCES_DISEASE,
  SAMPLED_FROM_SOURCE,
  SAMPLED_FROM_SPECIES,
  SAMPLED_FROM_SUBJECT,
  SAMPLE_PREP_LINKED_TO_METADATA,
  SAMPLE_TAKEN_FROM,
  SAMPLE_USES_FACTOR_LEVEL,
  STUDY_PRODUCED_ANALYSIS,
  STUDY_PRODUCED_ANOVA,
  STUDY_REFERENCES_METABOLITE,
  STUDY_REFERENCES_SOURCE,
  STUDY_REFERENCES_UNIQUE_SA,
  TREATMENT_LINKED_TO_METADATA,
  UNIQUE_SA_SAMPLED_FROM_SOURCE,
  NODES,
  NODE_PROPERTIES,
  RELATIONSHIPS,
  PATHWAYS,
};

export default schema;
