import Link from "next/link"
import Image from "next/image"

import Grid from '@mui/material/Grid'
import Container from '@mui/material/Container'
import Stack from '@mui/material/Stack'
import Chip from '@mui/material/Chip'

import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Paper from '@mui/material/Paper'
import Divider from '@mui/material/Divider'

import Carousel from '@/components/misc/Carousel/ServerCarousel'
import Twitter from '@/components/misc/Twitter'
import CFPrograms from "@/components/misc/CFPrograms"
import Outreach from "@/components/misc/Outreach"
import Icon from '@mdi/react';
import { mdiArrowRight } from "@mdi/js"
import { BlurSmall } from "@/components/styled/Blur"
import prisma from "@/lib/prisma"
import SimplePublicationComponent from "@/components/misc/Publication/SimplePublicationComponent"
export default async function Home() {
  const publications = await prisma.publication.findMany({
    orderBy: {
      year: "desc"
    },
    take: 5
  })
  return (
    <main>
      <Grid container spacing={2} alignItems={"center"}>
        <Grid item xs={12}>
          <Paper color="primary" elevation={0} sx={{
                        background: "#FFF",
                        padding: 5, 
                        borderRadius: 0, 
                        width: "100vw", 
                        minHeight: "100vh",
                        color: "#FFF",
                        marginLeft: "calc((-100vw + 100%) / 2)", 
                        marginRight: "calc((-100vw + 100%) / 2)",
                        overflow: "hidden",
                      }}
                  className="relative"
            >
            <BlurSmall sx={{position: 'absolute', top: -100, right: -100}}/>
            <BlurSmall sx={{position: 'absolute', bottom: -100, left: -100}}/>
            <Container maxWidth="lg">
              <Grid container spacing={2} alignItems={"flex-start"}>
                <Grid item xs={12} md={9}>
                  <Grid container spacing={2} alignItems={"center"} sx={{width :640}}>
                    <Grid item xs={12}>
                      <Carousel/>
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="h1" color="secondary" sx={{textTransform: "uppercase"}}>
                        Accelerating discovery by integrating Common Fund datasets
                      </Typography>
                      <Typography variant="body1" color="secondary">
                        The Common Fund Data Ecosystem (CFDE) aims to enable broad use of data generated by Common Fund Programs to accelerate hypothesis generation and discovery.
                      </Typography>
                      <Link href="/info/about">
                        <Button 
                          sx={{textTransform: "uppercase", marginLeft: -2}}
                          color="secondary"
                          endIcon={<Icon path={mdiArrowRight} size={1} />}>
                            Read More
                        </Button>
                      </Link>
                    </Grid>
                    <Grid item xs={12} md={6} className="flex items-center justify-center" sx={{marginTop: 5}}>
                      <Image  src="/img/UMAP.png" alt="side_pic" width={350} height={244}/>
                    </Grid>
                    <Grid item xs={12} md={6} sx={{marginTop: 5}}>
                      <Stack spacing={2}>
                        <Typography variant="h2" color={"secondary"}>
                          Data resource and knowledge centers
                        </Typography>
                        <Typography variant="body1" color={"secondary"}>
                          The Data Resource and Knowledge Centers aims to make Common Fund-generated data and resources more FAIR (Findable, Accessible, Interoperable, and Reusable).
                        </Typography>
                        <Link href="/info/about">
                          <Button
                            sx={{textTransform: "uppercase", marginLeft: -2}}
                            color="secondary"
                            endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              Discover DRC & KC
                          </Button>
                        </Link>
                      </Stack>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid item xs={12} md={3} sx={{
                    borderLeft: 2,
                    borderColor: "#7187C3"
                  }}>
                      <Stack spacing={2}>
                        <Link href="/info/outreach"><Typography sx={{color: "#FFF", background: "#7187c3", textAlign: "center", width: 233}}variant="subtitle1">TRAINING & OUTREACH</Typography></Link>
                        <Outreach orientation="vertical"/> 
                        {/* <Link href="/info/outreach"><Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}><Typography variant="subtitle1">See More</Typography></Button></Link> */}
                        <Paper elevation={0}>
                          <Typography sx={{color: "#FFF", background: "#7187c3", textAlign: "center", width: 233}}variant="subtitle1">RESOURCES</Typography>
                          <Link href='/data'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              DATA PORTAL
                            </Button>
                          </Link>
                          <Link href='/data/coming_soon'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              KNOWLEDGE PORTAL
                            </Button>
                          </Link>
                          <Link href='/info/dcc'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              DCCS
                            </Button>
                          </Link>
                          <Link href='/info/coming_soon'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              STANDARDS & PROTOCOLS
                            </Button>
                          </Link>
                        </Paper>
                        <Divider/>
                        <Paper elevation={0}>
                          <Typography sx={{color: "#FFF", background: "#7187c3", textAlign: "center", width: 233}}variant="subtitle1">COMMUNITY</Typography>
                          <Link href='/info/coming_soon'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              PARTNERSHIPS
                            </Button>
                          </Link>
                          <Link href='/info/outreach'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              TRAINING & OUTREACH
                            </Button>
                          </Link>
                          <Link href='/info/coming_soon'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              PRODUCTS
                            </Button>
                          </Link>
                          <Link href='/info/publications'>
                            <Button color="tertiary" endIcon={<Icon path={mdiArrowRight} size={1} />}>
                              PUBLICATIONS
                            </Button>
                          </Link>
                        </Paper>
                      </Stack>
                </Grid>
              </Grid>
            </Container>
          </Paper>
        </Grid>
        <Grid item xs={12} md={5}>
          <Stack spacing={2}>
            <Typography variant="h2" color="secondary" sx={{textTransform: 'uppercase'}}>
              Common Fund programs partnered with the CFDE
            </Typography>
            <Typography variant="body1" color="secondary" sx={{width: "95%"}}>
              The NIH Common Fund is a funding entity within the NIH that supports bold scientific programs that catalyze discovery across all biomedical and behavioral research.
            </Typography>
            <Link href="/info/dcc">
              <Button color="secondary" sx={{marginLeft: -2}} endIcon={<Icon path={mdiArrowRight} size={1} />}>
                <Typography variant="subtitle1">
                  Explore CF Programs
                </Typography>
              </Button>
            </Link>
          </Stack>
        </Grid>
        <Grid item xs={12} md={1}></Grid>
        <Grid item xs={12} md={6}>
          <CFPrograms baseEndpoint="/info/dcc" spacing={2}/>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Grid container spacing={2} justifyContent="center" alignItems={"center"}>
            <Grid item>
              <Paper sx={{
                borderRadius: 5, 
                height: 300, 
                width: "928px", 
                color: "#FFF", 
                background: "#336699",
                border:3,
                borderColor: "#C3E1E6", 
                boxShadow: 0,
                position: "relative",
                overflow: "hidden"
              }}>
                <Grid container spacing={2} sx={{height: 300}} justifyContent={"space-around"} alignItems={"center"}>
                  <Grid item sx={{width: 400}}>
                    <Typography variant={"h1"} sx={{textTransform: "uppercase"}} color="inherit">
                      Standards and Protocols
                    </Typography>
                    <Typography variant={"subtitle1"} color="inherit">
                      Learn more about the standards and protocols for accessing and submitting data to the portal
                    </Typography>
                  </Grid>
                <Grid item>
                  <Link href="/">
                    <Button variant="contained" sx={{borderRadius: 2}} color="primary">Find Out More</Button>
                  </Link>
                </Grid>
              </Grid>
              <BlurSmall sx={{
                backgroundColor: "#C3E1E6",
                position: 'absolute', 
                bottom: -180, 
                right: "30%"
              }}/>
            </Paper>
          </Grid>
        </Grid>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 5}}>
          <Paper sx={{
                        boxShadow: "none", 
                        background: '#EDF0F8',
                        padding: 10, 
                        borderRadius: 5, 
                        width: "100vw", 
                        marginLeft: "calc((-100vw + 100%) / 2)", 
                        marginRight: "calc((-100vw + 100%) / 2)"}}>
            <Container maxWidth="lg">
                <Grid container spacing={2} justifyContent="center" alignItems={"center"}>
                  <Grid item xs={12} sx={{marginBottom: 10}}>
                      <Grid container spacing={2}>
                        <Grid item xs={12} md={6} className="flex items-center justify-center">
                          <Link href="https://fairshake.cloud/" target="_blank" rel="noopener noreferrer">
                            <Image  src="/img/FAIR.png" alt="fair" width={400} height={400}/>
                          </Link>
                        </Grid>
                        <Grid item xs={12} md={6}>
                          <Typography variant={"h2"} color="secondary">
                            Making data more FAIR
                          </Typography>
                          <Typography variant={"subtitle1"}>
                            The Data Resource and Knowledge Centers are dedicated to enhancing the accessibility and utility of Common Fund-generated data and resources, striving to uphold the FAIR principles. This commitment serves as a catalyst for groundbreaking biomedical discoveries, fostering synergies across the diverse datasets within the Common Fund ecosystem, thereby unlocking novel avenues of research and innovation.
                          </Typography>
                          <div  className="mt-5">
                            <Link href="https://www.nature.com/articles/sdata201618" target="_blank" rel="noopener noreferrer">
                              <Button color="secondary">
                                <Typography variant={"subtitle1"}>
                                  What is FAIR?
                                </Typography>
                              </Button>
                            </Link>
                          </div>
                          <div  className="ml-8">
                            <ul>
                              <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Findable</Typography></li>
                              <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Accessible</Typography></li>
                              <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Interoperable</Typography></li>
                              <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Reusable</Typography></li>
                            </ul>
                          </div>
                        </Grid>
                      </Grid>
                  </Grid>
                  <Grid item xs={6}>
                    <Twitter/>
                  </Grid>
                  <Grid item xs={6}>
                    <Typography sx={{color: "#FFF", background: "#7187c3", textAlign: "center", width: 120}}variant="subtitle1">PUBLICATIONS</Typography>
                    <SimplePublicationComponent publications={publications}/>
                    <Link href={"/info/publications"}>
                      <Button color="secondary" variant="outlined">
                        Show More
                      </Button>
                    </Link>
                  </Grid>
              </Grid>
            </Container>
          </Paper>
        </Grid>
      </Grid>
    </main>
  )
}
