import Link from "next/link"
import Image from "next/image"
import { PrismaClient } from "@prisma/client"

import Grid from '@mui/material/Grid'
import Container from '@mui/material/Container'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Paper from '@mui/material/Paper'
import Chip from '@mui/material/Chip'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'

import Carousel from '@/components/misc/ServerCarousel'
import Twitter from '@/components/misc/Twitter'
const prisma = new PrismaClient()

async function CFPrograms() {
  const dccs = await prisma.dCC.findMany()
  return (
    <Grid container direction="row" spacing={2}>
      {dccs.map(dcc=>(
        <Grid item xs={6} md={4} key={dcc.short_label} className="flex items-center justify-center">
          <Link href={dcc.homepage} target="_blank" rel="noopener noreferrer"><Image src={dcc.icon || ''} alt={dcc.id} width={120} height={120}/></Link>
        </Grid>
      ))}
    </Grid>
  )
}

async function Publications() {
  const publications = await prisma.publication.findMany({
    orderBy: [
      {
        year: 'desc'
      }
    ],
    take: 5
  })
  return (
    <Paper sx={{boxShadow: "none", height: 500}}>
      {publications.map((pub, i)=>(
        <div key={i} style={{marginBottom: 10}}>
          <Link href={pub.doi || ''}>
            <Typography variant="caption">
              {pub.authors}. {pub.year}. <b>{pub.title}.</b> {pub.journal}. {pub.volume}. {pub.page}
            </Typography>
          </Link>
        </div>
      ))}
    </Paper>
  )
}

export function Outreach() {
  return (
    <>
      <Grid item xs={12}>
        <Card sx={{ height: 450, padding: 5 }}>
          {/* <CardMedia
            sx={{ height: 140 }}
            image="/img/Bridge2AI.png"
            title="CrossPollination"
          /> */}
          <CardContent>
            <Stack spacing={2}>
              <Chip color="secondary" label="FEATURED" sx={{width: 150}}/>
              <Typography variant="h3">Bridge 2AI - Cross Pollination</Typography>
              <Typography variant="subtitle1">Lorem ipsum dolor sit amet consectetur. Et nunc sit morbi quis id tellus praesent tempor. Tellus convallis amet sed suspendisse. Scelerisque vulputate quis convallis rhoncus nec eget tortor adipiscing.</Typography>
              <Typography variant="subtitle1">Date:  October 3, 2023</Typography>
            </Stack>
          </CardContent>
        </Card>
      </Grid>
      <Grid item xs={12} md={6}>
        <Card sx={{ height: 450, padding: 5 }}>
          {/* <CardMedia
            sx={{ height: 140 }}
            image="/img/LINCS.gif"
            title="CrossPollination"
          /> */}
          <CardContent>
            <Stack spacing={2}>
              <Chip color="secondary" label="ONLINE" sx={{width: 150}}/>
              <Typography variant="h3">Coursera: Network Analysis in Systems Biology</Typography>
              <Typography variant="subtitle1">Lorem ipsum dolor sit amet consectetur. Et nunc sit morbi quis id tellus praesent tempor. Tellus convallis amet sed suspendisse. Scelerisque vulputate quis convallis rhoncus nec eget tortor adipiscing.</Typography>
              <Link href="/"><Typography variant="subtitle1">Link</Typography></Link>
            </Stack>
          </CardContent>
        </Card>
      </Grid>
      <Grid item xs={12} md={6}>
        <Card sx={{ height: 450, padding: 5}}>
          {/* <CardMedia
            sx={{ height: 140 }}
            image="/img/GTEx.png"
            title="CrossPollination"
          /> */}
          <CardContent>
            <Stack spacing={2}>
              <Chip color="secondary" label="IN PERSON" sx={{width: 150}}/>
              <Typography variant="h3">GTEx In Person Training</Typography>
              <Typography variant="subtitle1">Lorem ipsum dolor sit amet consectetur. Et nunc sit morbi quis id tellus praesent tempor. Tellus convallis amet sed suspendisse. Scelerisque vulputate quis convallis rhoncus nec eget tortor adipiscing.</Typography>
              <Link href="/"><Typography variant="subtitle1">Date: December 6, 2023</Typography></Link>
            </Stack>
          </CardContent>
        </Card>
      </Grid>
    </>
  )
}



export default async function Home() {
  return (
    <main className="mt-24">
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Stack spacing={3}>
            <Typography variant="caption" color={"primary"}>Common Fund Data Ecosystem Workbench</Typography>
            <Typography variant="h1" color="primary">
              Accelerating discovery using Common Fund Data
            </Typography>
            <Typography variant="subtitle1">
              The Common Fund Data Ecosystem (CFDE) aims to enable broad use of data generated by Common Fund Programs to accelerate hypothesis generation and discovery.
            </Typography>
            <Link href="/about">
              <Button variant="outlined" color="secondary">
                Learn More
              </Button>
            </Link>
          </Stack>
        </Grid>
        <Grid item xs={6} className="flex items-center justify-center">
          <Carousel/>
        </Grid>
        <Grid item xs={3} sx={{marginTop: 10}}>
          <Stack spacing={3}>
            <Typography variant="h2" color="primary">
              Common Fund programs partnered with CFDE
            </Typography>
            <Typography variant="subtitle1">
            The NIH Common Fund is a funding entity within the NIH that supports bold scientific programs that catalyze discovery across all biomedical and behavioral research.
            </Typography>
          </Stack>
        </Grid>
        <Grid item xs={9} sx={{marginTop: 10}}><CFPrograms/></Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Paper sx={{boxShadow: "none", background: '#FAFAFA', padding: 5, borderRadius: 15}}>
            <Grid container spacing={2}>
              <Grid item xs={12} md={6} className="flex items-center justify-center">
                <Image src="/img/FAIR.png" alt="fair" width={400} height={400}/>
              </Grid>
              <Grid item xs={12} md={6}>
                <Typography variant={"h2"} color="primary">
                  Making data more FAIR
                </Typography>
                <Typography variant={"subtitle1"}>
                  The Data Resource and Knowledge Centers are dedicated to enhancing the accessibility and utility of Common Fund-generated data and resources, striving to uphold the FAIR principles. This commitment serves as a catalyst for groundbreaking biomedical discoveries, fostering synergies across the diverse datasets within the Common Fund ecosystem, thereby unlocking novel avenues of research and innovation.
                </Typography>
                <div  className="mt-5">
                  <Typography variant={"subtitle1"}>
                    What is FAIR?
                  </Typography>
                </div>
                <div  className="ml-8">
                  <ul>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Findable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Accessible</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Interoperable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Reusable</Typography></li>
                  </ul>
                </div>
              </Grid>
            </Grid>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Paper sx={{
                      boxShadow: "none", 
                      background: '#FAFAFA',
                      padding: 5, 
                      borderRadius: 0, 
                      width: "100vw", 
                      marginLeft: "calc((-100vw + 100%) / 2)", 
                      marginRight: "calc((-100vw + 100%) / 2)"}}>
            <Container maxWidth={"lg"}>
              <Grid container spacing={2} justifyContent={"space-between"} alignItems={"center"}>
                <Grid item>
                  <Typography variant={"h2"}>
                    Standards & Protocols
                  </Typography>
                  <Typography variant={"subtitle1"}>
                    Learn more about the standards and protocols for accessing and submitting data to the portal
                  </Typography>
                </Grid>
                <Grid item>
                  <Link href="/">
                    <Button variant="contained" color="secondary">Find Out More</Button>
                  </Link>
                </Grid>
              </Grid>
            </Container>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10, textAlign: "center"}}>
          <Typography variant={"h2"}>
            Training & Outreach
          </Typography>
        </Grid>
        <Outreach/>
        <Grid item xs={12} md={6} className="flex items-center justify-center" sx={{marginTop: 10, height: 500}}>
          <Stack>
            <Typography variant="h2">Twitter</Typography>
            <Twitter/>
          </Stack>
        </Grid>
        <Grid item xs={12} md={6} className="flex items-center justify-center" sx={{marginTop: 10}}>
          <Stack>
            <Typography variant="h2">Publications</Typography>
            <Publications/>
          </Stack>
        </Grid>
      </Grid>
    </main>
  )
}
