import Link from "next/link"
import Image from "next/image"
import { PrismaClient } from "@prisma/client"

import Grid from '@mui/material/Grid'
import Container from '@mui/material/Container'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Paper from '@mui/material/Paper'
import Carousel from '@/components/misc/ServerCarousel'
import Twitter from '@/components/misc/Twitter'
import CFPrograms from "@/components/misc/CFPrograms"
import Outreach from "@/components/misc/Outreach"

const prisma = new PrismaClient()


async function Publications() {
  const publications = await prisma.publication.findMany({
    orderBy: [
      {
        year: 'desc'
      }
    ],
    take: 5
  })
  return (
    <Paper sx={{boxShadow: "none", height: 500}}>
      {publications.map((pub, i)=>(
        <div key={i} style={{marginBottom: 10}}>
          <Link href={pub.doi || ''}>
            <Typography variant="caption">
              {pub.authors}. {pub.year}. <b>{pub.title}.</b> {pub.journal}. {pub.volume}. {pub.page}
            </Typography>
          </Link>
        </div>
      ))}
      <Button variant="outlined" color="secondary">See More</Button>
    </Paper>
  )
}

export default async function Home() {
  return (
    <main className="mt-24">
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Stack spacing={3}>
            <Typography variant="caption" color={"primary"}>The Common Fund Data Ecosystem Workbench</Typography>
            <Typography variant="h1" color="primary">
              Accelerating discovery by integrating Common Fund datasets
            </Typography>
            <Typography variant="subtitle1">
              The Common Fund Data Ecosystem (CFDE) aims to enable broad use of data generated by Common Fund Programs to accelerate hypothesis generation and discovery.
            </Typography>
            <Link href="/info/about">
              <Button variant="outlined" color="secondary">
                Learn More
              </Button>
            </Link>
          </Stack>
        </Grid>
        <Grid item xs={6} className="flex items-center justify-center">
          <Carousel/>
        </Grid>
        <Grid item xs={3} sx={{marginTop: 10}}>
          <Stack spacing={3}>
            <Typography variant="h2" color="primary">
              Common Fund programs partnered with the CFDE
            </Typography>
            <Typography variant="subtitle1">
            The NIH Common Fund is a funding entity within the NIH that supports bold scientific programs that catalyze discovery across all biomedical and behavioral research.
            </Typography>
          </Stack>
        </Grid>
        <Grid item xs={9} sx={{marginTop: 10}}><CFPrograms spacing={4}/></Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Paper sx={{boxShadow: "none", background: '#FAFAFA', padding: 5, borderRadius: 15}}>
            <Grid container spacing={2}>
              <Grid item xs={12} md={6} className="flex items-center justify-center">
                <Link href="https://fairshake.cloud/" target="_blank" rel="noopener noreferrer"><Image src="/img/FAIR.png" alt="fair" width={400} height={400}/></Link>
              </Grid>
              <Grid item xs={12} md={6}>
                <Typography variant={"h2"} color="primary">
                  Making data more FAIR
                </Typography>
                <Typography variant={"subtitle1"}>
                  The Data Resource and Knowledge Centers are dedicated to enhancing the accessibility and utility of Common Fund-generated data and resources, striving to uphold the FAIR principles. This commitment serves as a catalyst for groundbreaking biomedical discoveries, fostering synergies across the diverse datasets within the Common Fund ecosystem, thereby unlocking novel avenues of research and innovation.
                </Typography>
                <div  className="mt-5">
                  <Link href="https://www.nature.com/articles/sdata201618" target="_blank" rel="noopener noreferrer">
                    <Button color="secondary">
                      <Typography variant={"subtitle1"}>
                        What is FAIR?
                      </Typography>
                    </Button>
                  </Link>
                </div>
                <div  className="ml-8">
                  <ul>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Findable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Accessible</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Interoperable</Typography></li>
                    <li style={{listStyleType: "disc"}}><Typography variant={"subtitle1"}>Reusable</Typography></li>
                  </ul>
                </div>
              </Grid>
            </Grid>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10}}>
          <Paper sx={{
                      boxShadow: "none", 
                      background: '#FAFAFA',
                      padding: 5, 
                      borderRadius: 0, 
                      width: "100vw", 
                      marginLeft: "calc((-100vw + 100%) / 2)", 
                      marginRight: "calc((-100vw + 100%) / 2)"}}>
            <Container maxWidth={"lg"}>
              <Grid container spacing={2} justifyContent={"space-between"} alignItems={"center"}>
                <Grid item>
                  <Typography variant={"h2"}>
                    Standards & Protocols
                  </Typography>
                  <Typography variant={"subtitle1"}>
                    Learn more about the standards and protocols for accessing and submitting data to the portal
                  </Typography>
                </Grid>
                <Grid item>
                  <Link href="/">
                    <Button variant="contained" color="secondary">Find Out More</Button>
                  </Link>
                </Grid>
              </Grid>
            </Container>
          </Paper>
        </Grid>
        <Grid item xs={12} sx={{marginTop: 10, textAlign: "center"}}>
          <Typography variant={"h2"}>
            Training & Outreach
          </Typography>
        </Grid>
        <Outreach/>
        <Grid item xs={12} md={6} className="flex items-center justify-center" sx={{marginTop: 10, height: 500}}>
          <Stack>
            <Typography variant="h2">Social Media</Typography>
            <Twitter/>
          </Stack>
        </Grid>
        <Grid item xs={12} md={6} className="flex items-center justify-center" sx={{marginTop: 10}}>
          <Stack>
            <Typography variant="h2">Publications</Typography>
            <Publications/>
          </Stack>
        </Grid>
      </Grid>
    </main>
  )
}
