'use client'
import { MarkdownStatic } from '@/components/misc/MarkdownComponent';
import { Stack } from '@mui/material';
import React from 'react';
import MDT from './mdt';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';

const tabs = [
	{
		name: "NCBI Description",
		field: "description"
	},
	{
		name: "DeepDive GPT-4 Summary",
		field: "deepdive_gpt4o_description"
	},
	{
		name: "DeepDive Gemini Summary",
		field: "deepdive_gemini_description"
	},
]


function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

const GeneSummary = (props: { summary: {[key:string]: string}}) => {
	const [value, setValue] = React.useState(0);
	const handleChange = (event: React.SyntheticEvent, newValue: number) => {
		setValue(newValue);
	};
	return (
		<Box sx={{ width: '100%' }}>
			<Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 1 }}>
				<Tabs textColor="secondary"
					indicatorColor="secondary"
					value={value} onChange={handleChange} aria-label="Description">
					{tabs.map((tab, index)=><Tab key={tab.name} label={tab.name} {...a11yProps(index)} />)}
				</Tabs>
			</Box>
			{value === 0 ?
				<MarkdownStatic markdown={props.summary.description}/>:
				<Stack>
					<MDT src={(props.summary[tabs[value].field])}/>
					<p><i>Generated by summarizing the top 50 most cited paper abstracts that mention this gene using gpt4o-mini (DeepDive).</i></p>
				</Stack>
			}
		</Box>
	)
}

export default GeneSummary